addons:
  apt:
    packages:
      zsh
dist: trusty
before_script:
- mkdir .bin
- curl -L https://raw.githubusercontent.com/molovo/revolver/master/revolver > .bin/revolver
- curl -L https://raw.githubusercontent.com/molovo/color/master/color.zsh > .bin/color
- chmod u+x .bin/{color,revolver}
- export PATH="$PWD/.bin:$PATH"
script: ./zunit
